---
- hosts: web
  tasks:
          - name: Create multiple users
            user:
                    name: "{{item}}"
                    state: present
            with_items:
                    - testuser1
                    - testuser2
          - name: Install multiple packages
            package:
                    name: "{{item}}"
                    state: present
            with_items:
                    - apache2
                    - mysql-client
                    - vim
                    - gcc
          - name: Install multiple packages
            apt:
                    name: ['apache2','mysql-client','vim','gcc']
                    state: present
