---
- hosts: web
  tasks:
          - name: Install package
            apt:
                    name: ntp
                    state: present
          - name: Service status
            service:
                    name: ntp
                    state: stopped

