---
- hosts: web
  tasks:
          - name: Install package
            apt:
                    name: apache2
                    state: present
          - name: Create Directory
            file:
                    name: /var/www/html/webapp
                    mode: 0777
                    state: directory
          - name: Create File
            file:
                    name: /var/www/html/webapp/index.html
                    state: touch
          - name: Copy File
            copy:
                    src: index.html.j2
                    dest: /var/www/html/webapp/cntrlindexcpy.html
          - name: Template module to copy file
            template:
                    src: index.html.j2
                    dest: /var/www/html/webapp/cntrlindextmpl.html
          - name: Create user
            user:
                    name: devops
                    state: present
          - name: Install package
            apt:
                    name: apache2
                    state: present
          - name: Start Service
            service:
                    name: apache2
                    state: started
